# Generated by Django 5.1.2 on 2024-10-27 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic_center', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostic_center',
            name='marketing_executive',
        ),
    ]
