# Generated by Django 5.1.2 on 2024-10-27 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostic_center', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('test_details', models.CharField(max_length=100)),
                ('rate', models.IntegerField()),
                ('payment_status', models.CharField(choices=[('P', 'Paid'), ('D', 'Due')], max_length=2)),
                ('diagnostic_center', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diagnostic_center.diagnostic_center')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='locations.location')),
            ],
        ),
    ]
