# Generated by Django 5.1.2 on 2024-10-27 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('marketing_executive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic_Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='locations.location')),
                ('marketing_executive', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='marketing_executive.marketing_executive')),
            ],
        ),
    ]
