# Generated by Django 5.1.2 on 2024-10-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=11)),
                ('salary', models.IntegerField()),
                ('target_amount', models.IntegerField()),
            ],
        ),
    ]
