# Generated by Django 5.1.2 on 2024-10-30 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('marketing_executive', '0003_alter_marketing_executive_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing_executive',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
    ]
