# Generated by Django 5.1.2 on 2024-11-06 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='marketing_executive',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Paid'), ('D', 'Due')], default='D', max_length=2),
        ),
    ]
