# Generated by Django 5.1.2 on 2024-11-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0003_investigation_investigation_slip_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='investigation_slip_img',
            field=models.ImageField(blank=True, null=True, upload_to='investigations/media/investigation_slips/'),
        ),
    ]
