# Generated by Django 5.1.2 on 2024-11-03 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_executive', '0004_alter_marketing_executive_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marketing_Executive',
        ),
    ]
