# Generated by Django 5.1.2 on 2024-11-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=50)),
                ('task_description', models.TextField(max_length=200)),
                ('task_is_completed', models.BooleanField(default=False)),
                ('task_assign_date', models.DateField(auto_now=True)),
                ('task_category', models.ManyToManyField(to='category.taskcategorymodel')),
            ],
        ),
    ]
